import { ImageResponse } from '@vercel/og';
import { NextRequest } from 'next/server';

export const runtime = 'edge';

export async function GET(req: NextRequest) {
  try {
    const { searchParams } = new URL(req.url);
    const title = searchParams.get('title');
    const invoiceNumber = searchParams.get('invoiceNumber');
    const customerName = searchParams.get('customerName');

    return new ImageResponse(
      (
        <div
          style={{
            height: '100%',
            width: '100%',
            display: 'flex',
            flexDirection: 'column',
            alignItems: 'center',
            justifyContent: 'center',
            backgroundColor: '#ffffff',
            backgroundImage: 'linear-gradient(to bottom right, #ffffff, #f8fafc)',
            padding: '40px 80px',
            position: 'relative',
          }}
        >
          {/* Decorative elements */}
          <div
            style={{
              position: 'absolute',
              top: 0,
              left: 0,
              right: 0,
              height: '4px',
              background: 'linear-gradient(to right, #3b82f6, #8b5cf6)',
            }}
          />

          <div
            style={{
              display: 'flex',
              flexDirection: 'column',
              alignItems: 'center',
              justifyContent: 'center',
              textAlign: 'center',
              maxWidth: '900px',
            }}
          >
            <div
              style={{
                fontSize: '24px',
                color: '#6b7280',
                marginBottom: '16px',
                letterSpacing: '0.1em',
                textTransform: 'uppercase',
                fontWeight: '500',
              }}
            >
              Professional Invoice
            </div>

            <h1
              style={{
                fontSize: '64px',
                fontWeight: '700',
                marginBottom: '24px',
                lineHeight: '1.2',
                background: 'linear-gradient(to right, #1e40af, #3b82f6)',
                backgroundClip: 'text',
                WebkitBackgroundClip: 'text',
                color: 'transparent',
              }}
            >
              {title || 'Invoice'}
            </h1>

            {invoiceNumber && (
              <div
                style={{
                  fontSize: '32px',
                  color: '#4b5563',
                  marginBottom: '16px',
                  padding: '8px 24px',
                  backgroundColor: '#f3f4f6',
                  borderRadius: '8px',
                  fontWeight: '500',
                }}
              >
                #{invoiceNumber}
              </div>
            )}

            {customerName && (
              <div
                style={{
                  fontSize: '28px',
                  color: '#6b7280',
                  marginTop: '16px',
                  display: 'flex',
                  alignItems: 'center',
                  gap: '8px',
                }}
              >
                <span style={{ color: '#4b5563' }}>For</span>
                <span style={{ color: '#1e40af', fontWeight: '500' }}>{customerName}</span>
              </div>
            )}
          </div>

          {/* Watermark */}
          <div
            style={{
              position: 'absolute',
              bottom: '24px',
              right: '24px',
              fontSize: '16px',
              color: '#9ca3af',
              opacity: 0.5,
            }}
          >
            Generated by Pulse
          </div>
        </div>
      ),
      {
        width: 1200,
        height: 630,
      },
    );
  } catch (e) {
    console.log(`${e.message}`);
    return new Response(`Failed to generate the image`, {
      status: 500,
    });
  }
}
