import { newRequest } from '@/utils/newRequest';
import { useInfiniteQuery } from '@tanstack/react-query';

interface EmailParticipant {
  id: number;
  avatar_type: string;
  class: string;
  source: string;
  url: string;
  namespace: string;
  name: string;
  card_name: string;
  handle: string;
  email: string | null;
  display_name: string;
  description: string | null;
  avatar: string;
  initials: string;
  channel_id: number | null;
  channel_full: {
    id: number;
    type: string;
    namespace: string;
    is_private: boolean;
    avatar_type: string;
    class: string;
    message_type: string;
    type_name: string;
    contact_source: string;
    url: string;
    display_name: string;
    address: string;
    send_as: string;
    two_way_sync: boolean;
    slowlaned: boolean;
    sync_status: string;
    account_status: string;
    primed: boolean;
    error_type: string | null;
    settings: Record<string, any>;
    deliv_settings: Record<string, any>;
    defer_rate: number;
    is_missing_calendar_scopes: boolean;
    is_sandbox: boolean;
    created_at: number;
    updated_at: number;
    inbox_id: number;
    inbox_alias: string;
    inbox_name: string;
    owner: string | null;
    error_desc: string | null;
    webhook_url_in: string;
    api_url: string;
    properties: Record<string, any>;
  } | null;
  inbox_alias: string | null;
  message_type: string | null;
  card_id: number;
  card_url: string;
  links: any[];
  num_notes: number;
  extra: {
    email: string | null;
  };
  card: {
    id: number;
    namespace: string;
    avatar_type: string;
    class: string;
    url: string;
    name: string;
    display_name: string;
    avatar: string;
    initials: string;
    color: string;
    num_notes: number;
    namespace_to_num_notes: Record<string, number>;
    autogenerated: boolean;
    edited: boolean;
    created_at: number;
    updated_at: number;
    type: string;
    bio: string | null;
    description: string | null;
    links: any[];
    groups: any[];
    external_info: any;
    custom_field_attributes: any[];
    contacts: Array<{
      id: number;
      url: string;
      source: string;
      handle: string;
    }>;
  };
  fallback: any;
  role: 'from' | 'to' | 'cc' | 'bcc';
  is_spammer: boolean;
  recipient_url: string;
}

interface EmailBody {
  text: string;
  html: string;
}

interface Attachment {
  filename: string;
  mimeType: string;
  size: number;
  attachmentId: string;
  storageUrl: string;
}

interface Token {
  accessToken: string;
  refreshToken: string;
  expiryDate: string;
  scope: string;
}

export interface InboxThread {
  _id: string;
  gmailMessageId: string;
  threadId: string;
  userId: string;
  workspaceId: string;
  from: EmailParticipant;
  to: EmailParticipant[];
  cc: EmailParticipant[];
  bcc: EmailParticipant[];
  subject: string;
  body: EmailBody;
  labels: string[];
  snippet: string;
  internalDate: string;
  attachments: Attachment[];
  isRead: boolean;
  historyId: string;
  threadPart: number;
  messageSource: string;
  rawHeaders: Record<string, any>;
  token: Token;
  syncedAt: string;
  createdAt: string;
  updatedAt: string;
  __v: number;
}

interface PaginatedResponse {
  success: boolean;
  data: InboxThread[];
  pagination: {
    total: number;
    page: number;
    pages: number;
    limit: number;
  };
}

const fetchInboxThreads = async ({ pageParam = 1 }): Promise<PaginatedResponse> => {
  const { data } = await newRequest.get('/inbox', {
    params: {
      page: pageParam,
      limit: 10,
    },
  });
  return data;
};

export const useInbox = () => {
  return useInfiniteQuery({
    queryKey: ['inbox-threads'],
    queryFn: fetchInboxThreads,
    getNextPageParam: (lastPage) => {
      if (lastPage.pagination.page < lastPage.pagination.pages) {
        return lastPage.pagination.page + 1;
      }
      return undefined;
    },
    initialPageParam: 1,
  });
};
