import { newRequest } from '@/utils/newRequest';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useState } from 'react';

interface Stage {
  _id: string;
  name: string;
  order: number;
  color: string;
}

interface Status {
  _id: string;
  name: string;
  order: number;
  color: string;
}

interface PipelineSettings {
  workspace: string;
  _id: string;
  stages: Stage[];
  statuses: Status[];
  createdAt: string;
  updatedAt: string;
  __v: number;
}

export function usePipelineSettings() {
  const queryClient = useQueryClient();
  const [isEditStatusDialogOpen, setIsEditStatusDialogOpen] = useState(false);
  const [newStageName, setNewStageName] = useState('');
  const [newStatusName, setNewStatusName] = useState('');
  const [newStatusColor, setNewStatusColor] = useState('slate');
  const [customColor, setCustomColor] = useState('#94a3b8');
  const [editingStageIndex, setEditingStageIndex] = useState<number | null>(null);
  const [editingStatusIndex, setEditingStatusIndex] = useState<number | null>(null);
  const [isAddingStage, setIsAddingStage] = useState(false);

  // Fetch pipeline settings
  const { data: pipelineSettings, isLoading } = useQuery<PipelineSettings>({
    queryKey: ['pipelineSettings'],
    queryFn: async () => {
      const response = await newRequest.get('/pipeline/settings');
      return response.data;
    },
  });

  // Update stages mutation
  const updateStagesMutation = useMutation({
    mutationFn: async (newStages: Stage[]) => {
      return await newRequest.put('/pipeline/settings/stages', { stages: newStages });
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['pipelineSettings'] });
    },
  });

  // Update statuses mutation
  const updateStatusesMutation = useMutation({
    mutationFn: async (newStatuses: Status[]) => {
      return await newRequest.put('/pipeline/settings/statuses', { statuses: newStatuses });
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['pipelineSettings'] });
    },
  });

  const handleAddStage = () => {
    if (newStageName.trim() && pipelineSettings) {
      const updatedStages = [...pipelineSettings.stages];
      const newStage: Stage = {
        _id: '', // This will be generated by the backend
        name: newStageName,
        order: updatedStages.length,
        color: customColor,
      };

      if (editingStageIndex !== null) {
        updatedStages[editingStageIndex] = {
          ...updatedStages[editingStageIndex],
          name: newStageName,
          color: customColor,
        };
      } else {
        updatedStages.push(newStage);
      }
      updateStagesMutation.mutate(updatedStages);
      setNewStageName('');
      setCustomColor('#94a3b8');
      setEditingStageIndex(null);
      setIsAddingStage(false);
    }
  };

  const handleDeleteStage = (index: number) => {
    if (pipelineSettings) {
      const updatedStages = [...pipelineSettings.stages];
      updatedStages.splice(index, 1);
      // Update order for remaining stages
      updatedStages.forEach((stage, i) => {
        stage.order = i;
      });
      updateStagesMutation.mutate(updatedStages);
    }
  };

  const handleEditStage = (index: number) => {
    if (pipelineSettings) {
      setNewStageName(pipelineSettings.stages[index].name);
      setCustomColor(pipelineSettings.stages[index].color);
      setEditingStageIndex(index);
      setIsAddingStage(true);
    }
  };

  const handleEditStatus = (index: number) => {
    if (pipelineSettings) {
      setNewStatusName(pipelineSettings.statuses[index].name);
      setCustomColor(pipelineSettings.statuses[index].color);
      setEditingStatusIndex(index);
      setIsEditStatusDialogOpen(true);
    }
  };

  const handleUpdateStatus = () => {
    if (newStatusName.trim() && editingStatusIndex !== null && pipelineSettings) {
      const updatedStatuses = [...pipelineSettings.statuses];
      updatedStatuses[editingStatusIndex] = {
        ...updatedStatuses[editingStatusIndex],
        name: newStatusName,
        color: customColor,
      };
      updateStatusesMutation.mutate(updatedStatuses);
      setNewStatusName('');
      setCustomColor('#94a3b8');
      setEditingStatusIndex(null);
      setIsEditStatusDialogOpen(false);
    }
  };

  const handleDeleteStatus = (index: number) => {
    if (pipelineSettings) {
      const updatedStatuses = [...pipelineSettings.statuses];
      updatedStatuses.splice(index, 1);
      // Update order for remaining statuses
      updatedStatuses.forEach((status, i) => {
        status.order = i;
      });
      updateStatusesMutation.mutate(updatedStatuses);
    }
  };

  const moveStage = (index: number, direction: 'up' | 'down') => {
    if (!pipelineSettings) return;

    if (
      (direction === 'up' && index === 0) ||
      (direction === 'down' && index === pipelineSettings.stages.length - 1)
    ) {
      return;
    }

    const newIndex = direction === 'up' ? index - 1 : index + 1;
    const updatedStages = [...pipelineSettings.stages];
    [updatedStages[index], updatedStages[newIndex]] = [
      updatedStages[newIndex],
      updatedStages[index],
    ];

    // Update order for all stages
    updatedStages.forEach((stage, i) => {
      stage.order = i;
    });

    updateStagesMutation.mutate(updatedStages);
  };

  return {
    stages: pipelineSettings?.stages || [],
    statuses: pipelineSettings?.statuses || [],
    isEditStatusDialogOpen,
    newStageName,
    newStatusName,
    newStatusColor,
    customColor,
    editingStageIndex,
    editingStatusIndex,
    isAddingStage,
    isLoading,
    setNewStageName,
    setNewStatusName,
    setNewStatusColor,
    setCustomColor,
    setIsEditStatusDialogOpen,
    handleAddStage,
    handleDeleteStage,
    handleEditStage,
    handleEditStatus,
    handleUpdateStatus,
    handleDeleteStatus,
    moveStage,
    setEditingStageIndex,
    setEditingStatusIndex,
    setIsAddingStage,
  };
}
